{
  "formatVersion": "1.0",
  "component": {
    "url": "../../googletest/1.9.0-gr4-SNAPSHOT/googletest-1.9.0-gr4-SNAPSHOT.module",
    "group": "org.gradle.cpp-samples",
    "module": "googletest",
    "version": "1.9.0-gr4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "eellpq43argtznxrpbpoptxrma"
    }
  },
  "variants": [
    {
      "name": "debugLinuxRuntime",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.debuggable": true,
        "org.gradle.native.linkage": "SHARED",
        "org.gradle.native.operatingSystem": "linux",
        "org.gradle.native.optimized": false,
        "org.gradle.usage": "native-runtime"
      },
      "files": [
        {
          "name": "libgoogletest.so",
          "url": "googletest_debug_linux-1.9.0-gr4-SNAPSHOT.so",
          "size": 2012840,
          "sha1": "dcf756c3606ff4349309e65393913e3468df0764",
          "md5": "1debbeaaa611c780f20de36d5fa52ca5"
        }
      ]
    },
    {
      "name": "debugLinuxLink",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.debuggable": true,
        "org.gradle.native.linkage": "SHARED",
        "org.gradle.native.operatingSystem": "linux",
        "org.gradle.native.optimized": false,
        "org.gradle.usage": "native-link"
      },
      "files": [
        {
          "name": "libgoogletest.so",
          "url": "googletest_debug_linux-1.9.0-gr4-SNAPSHOT.so",
          "size": 2012840,
          "sha1": "dcf756c3606ff4349309e65393913e3468df0764",
          "md5": "1debbeaaa611c780f20de36d5fa52ca5"
        }
      ]
    }
  ]
}
