{
  "formatVersion": "1.0",
  "component": {
    "url": "../../googletest/1.9.0-gr4-SNAPSHOT/googletest-1.9.0-gr4-SNAPSHOT.module",
    "group": "org.gradle.cpp-samples",
    "module": "googletest",
    "version": "1.9.0-gr4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "bayu2b3a4vh6rlr4dhtzxirb6q"
    }
  },
  "variants": [
    {
      "name": "releaseWindowsLink",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.debuggable": true,
        "org.gradle.native.linkage": "SHARED",
        "org.gradle.native.operatingSystem": "windows",
        "org.gradle.native.optimized": true,
        "org.gradle.usage": "native-link"
      },
      "files": [
        {
          "name": "googletest.lib",
          "url": "googletest_release_windows-1.9.0-gr4-SNAPSHOT.lib",
          "size": 217054,
          "sha1": "60450559fd7fb682f1f7c7c205d590470fca27b7",
          "md5": "8863a35d66c75da2663d7d18829e28f3"
        }
      ]
    },
    {
      "name": "releaseWindowsRuntime",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.debuggable": true,
        "org.gradle.native.linkage": "SHARED",
        "org.gradle.native.operatingSystem": "windows",
        "org.gradle.native.optimized": true,
        "org.gradle.usage": "native-runtime"
      },
      "files": [
        {
          "name": "googletest.dll",
          "url": "googletest_release_windows-1.9.0-gr4-SNAPSHOT.dll",
          "size": 1716736,
          "sha1": "ca5515b2213bffa59cc41e2b430d37af185be3c0",
          "md5": "81d32b8eae8c98a095c30c453e4ca4cb"
        }
      ]
    }
  ]
}
